<script setup lang="ts">
import { computed, type Component } from 'vue';
import {
    ArrowRight,
    Award,
    Bot,
    Boxes,
    Braces,
    Brain,
    Briefcase,
    Bug,
    Calendar,
    Check,
    ChevronDown,
    CircleAlert,
    Cloud,
    Code,
    Container,
    Copy,
    Cpu,
    CreditCard,
    Database,
    Download,
    ExternalLink,
    FileCode,
    Gauge,
    GitBranch,
    Globe,
    GraduationCap,
    HardDrive,
    Layers,
    Lock,
    Mail,
    MapPin,
    MessageCircle,
    Monitor,
    Moon,
    Network,
    Package,
    Palette,
    Printer,
    Rocket,
    Search,
    Server,
    Settings,
    Shield,
    Smartphone,
    Sparkles,
    Star,
    Sun,
    Terminal,
    Webhook,
    Workflow,
    Wrench,
    X,
    Zap,
} from 'lucide-vue-next';
import GithubIcon from '@/components/icons/GithubIcon.vue';
import LinkedinIcon from '@/components/icons/LinkedinIcon.vue';
import TwitterIcon from '@/components/icons/TwitterIcon.vue';

const icons: Record<string, Component> = {
    // Brands (custom components)
    github: GithubIcon,
    linkedin: LinkedinIcon,
    twitter: TwitterIcon,
    x: TwitterIcon,
    mail: Mail,
    'external-link': ExternalLink,
    download: Download,
    'arrow-right': ArrowRight,
    calendar: Calendar,
    'map-pin': MapPin,
    sun: Sun,
    moon: Moon,
    check: Check,
    copy: Copy,
    'chevron-down': ChevronDown,
    message: MessageCircle,
    printer: Printer,
    'x-mark': X,
    close: X,
    database: Database,
    layers: Layers,
    cpu: Cpu,
    code: Code,
    cloud: Cloud,
    globe: Globe,
    sparkles: Sparkles,
    briefcase: Briefcase,
    award: Award,
    star: Star,
    'graduation-cap': GraduationCap,
    server: Server,
    terminal: Terminal,
    settings: Settings,
    wrench: Wrench,
    shield: Shield,
    lock: Lock,
    rocket: Rocket,
    zap: Zap,
    'git-branch': GitBranch,
    container: Container,
    boxes: Boxes,
    network: Network,
    'hard-drive': HardDrive,
    smartphone: Smartphone,
    monitor: Monitor,
    palette: Palette,
    bug: Bug,
    workflow: Workflow,
    package: Package,
    'file-code': FileCode,
    braces: Braces,
    bot: Bot,
    webhook: Webhook,
    gauge: Gauge,
    brain: Brain,
    'credit-card': CreditCard,
    search: Search,
};

const props = withDefaults(
    defineProps<{
        name?: string | null;
        className?: string;
    }>(),
    {
        name: null,
        className: 'w-4 h-4',
    },
);

const icon = computed<Component>(
    () => icons[props.name?.toLowerCase().trim() ?? ''] ?? CircleAlert,
);
</script>

<template>
    <component :is="icon" :class="className" aria-hidden="true" />
</template>
